### ISSUE TITLE
Check ROS library Arbotix-m for any missing parts.

### ISSUE THREAD

**Issue by rummens1337** [HvA-Robotics/kobuki-arm#22]

**Comment by MarijnStam** [comment]
The Arbotix ROS library has sufficient support for the handling of reads on the AX12 register.

We need to build a Publisher which sends an instruction to the ROS code on the Arbotix which then reads a register based on an address defined in the message of the Publisher. 

With this in place we can read any register. (Temperature, torque, volts etc..)
